name: Build FNA Native Libraries
on:
  schedule:
    # Let's do it every month on the 1st at 10:00 AM CST (aka 15:00 UTC)
    - cron: '0 15 1 * *'
jobs:
  # Build on all platforms (Windows, Linux, macOS)
  build:
    name: Build Libraries on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Checkout libraries
        run: |
          bundle exec ruby checkout.rb
      - name: Build libraries
        run: |
          bundle exec ruby build.rb
